version: '3.8'

services:

  db:
    image: postgres:9.6.21
    environment:
      POSTGRES_DB: @dockerSqlDatabase@
      POSTGRES_USER: @dockerSqlUser@
      POSTGRES_PASSWORD: @dockerSqlPassword@
    ports:
      - '25432:5432'
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: @dockerImageName@ # :@version@ - haven't figured out how to add yet
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'